DEFINE TASK {{db}}.RAW.INGEST_LOAN_TRANSACTIONS
    WAREHOUSE = BRF_INGEST_WH
    SCHEDULE = '30 MINUTE'
    STARTED
AS
    COPY INTO {{db}}.RAW.LOAN_TRANSACTIONS_RAW
    FROM @{{source_stage_db}}.RAW.LOAN_TRANSACTIONS_STG
    FILE_FORMAT = (FORMAT_NAME = '{{db}}.RAW.LOAN_TRANSACTIONS_FF')
    PATTERN = '.*\.csv\.gz'
    MATCH_BY_COLUMN_NAME = 'CASE_INSENSITIVE';
