DEFINE FILE FORMAT {{db}}.RAW.LOAN_TRANSACTIONS_FF
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('')
    EMPTY_FIELD_AS_NULL = TRUE
    COMPRESSION = 'GZIP';
