DEFINE TABLE {{db}}.RAW.LOAN_TRANSACTIONS_RAW (
    TRANSACTION_ID VARCHAR NOT NULL,
    LOAN_ID VARCHAR,
    APPLICANT_ID VARCHAR,
    EVENT_TYPE VARCHAR,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    PRODUCT_TYPE VARCHAR,
    CHANNEL VARCHAR,
    AMOUNT NUMBER(12,2),
    CURRENCY VARCHAR(3),
    OFFICER_ID VARCHAR,
    BRANCH_CODE VARCHAR,
    STATUS VARCHAR,
    NOTES VARCHAR,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT current_timestamp(),
    _SOURCE_FILE VARCHAR
);
