name: Deploy to UAT (PRODACC)

on:
  push:
    branches:
      - 'uat/**-UAT'

jobs:
  deploy:
    uses: sfc-gh-pfaulkner/snowflake-rbac-framework/.github/workflows/deploy-to-clone.yml@main
    with:
      clone_type: UAT
      environment: PROD
      domain: BRF
      db_name: CORE
      dcm_target: PROD
      role: PROD_BRF_ETL
      warehouse: BRF_WH
    secrets:
      SNOWFLAKE_ACCOUNT: ${{ secrets.PROD_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.PROD_USER }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
