name: Deploy to TEST (DEVACC)

on:
  push:
    branches:
      - 'test/**-TEST'

jobs:
  deploy:
    uses: sfc-gh-pfaulkner/snowflake-rbac-framework/.github/workflows/deploy-to-clone.yml@main
    with:
      clone_type: TEST
      environment: DEV
      domain: BRF
      db_name: CORE
      dcm_target: DEV
      role: DEV_BRF_ETL
      warehouse: BRF_WH
    secrets:
      SNOWFLAKE_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.DEV_USER }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
